## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
server:
  tomcat:
    max-http-form-post-size: 23MB
  servlet:
    context-path: /rest/v1
  port: 9898
  forward-headers-strategy: native
  error:
    include-message: always
    whitelabel:
      enabled: false
